// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemGw.Data;

namespace SystemGw.Migrations
{
    [DbContext(typeof(SystemContext))]
    partial class SystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SystemGw.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("SystemGw.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("SystemGw.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("SystemGw.Models.QuadroServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChassiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDaRota")
                        .HasColumnType("datetime2");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NomeClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("NomeMecanicoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroOs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatisfacaoComServico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SetorMecanicoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusDaMaquina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDoAtendimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusDoServicoId")
                        .HasColumnType("int");

                    b.Property<string>("TempoOsAberta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoOsId")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChassiId");

                    b.HasIndex("NomeClienteId");

                    b.HasIndex("NomeMecanicoId");

                    b.HasIndex("SetorMecanicoId");

                    b.HasIndex("StatusDoServicoId");

                    b.HasIndex("TipoOsId");

                    b.ToTable("QuadroServicos");
                });

            modelBuilder.Entity("SystemGw.Models.Regiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Regioes");
                });

            modelBuilder.Entity("SystemGw.Models.SetorMecanico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("SetorMecanicos");
                });

            modelBuilder.Entity("SystemGw.Models.StatusDoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("StatusDoServicos");
                });

            modelBuilder.Entity("SystemGw.Models.TipoOs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("TipoOs");
                });

            modelBuilder.Entity("SystemGw.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("SystemGw.Models.QuadroServico", b =>
                {
                    b.HasOne("SystemGw.Models.Veiculo", "Chassi")
                        .WithMany()
                        .HasForeignKey("ChassiId");

                    b.HasOne("SystemGw.Models.Pessoa", "NomeCliente")
                        .WithMany()
                        .HasForeignKey("NomeClienteId");

                    b.HasOne("SystemGw.Models.Funcionario", "NomeMecanico")
                        .WithMany()
                        .HasForeignKey("NomeMecanicoId");

                    b.HasOne("SystemGw.Models.SetorMecanico", "SetorMecanico")
                        .WithMany()
                        .HasForeignKey("SetorMecanicoId");

                    b.HasOne("SystemGw.Models.StatusDoServico", "StatusDoServico")
                        .WithMany()
                        .HasForeignKey("StatusDoServicoId");

                    b.HasOne("SystemGw.Models.TipoOs", "TipoOs")
                        .WithMany()
                        .HasForeignKey("TipoOsId");
                });
#pragma warning restore 612, 618
        }
    }
}
